name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Extract version from tag
        id: get_version
        run: |
          echo "##[set-output name=version;]${GITHUB_REF#refs/tags/v}"
        shell: bash

      - name: Update .csproj version
        run: |
          $version = "${{ steps.get_version.outputs.version }}"
          (Get-Content ZentrixLabs.FalconConsoleDemo.csproj) -replace '(<Version>).*?(</Version>)', "`$1$version`$2" | Set-Content ZentrixLabs.FalconConsoleDemo.csproj
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -c Release -o publish

      - name: Package build artifacts
        run: |
          cd publish
          Compress-Archive * ../ZentrixLabs.FalconConsoleDemo.zip
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ZentrixLabs.FalconConsoleDemo.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
