name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        run: |
          $version = "${{ github.ref_name }}"
          $version = $version -replace '^v', ''
          echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: powershell

      - name: Debug APP_VERSION
        run: echo "APP_VERSION is ${{ env.APP_VERSION }}"
        shell: powershell

      - name: Update .csproj version
        run: |
          $csprojPath = "ZentrixLabs.FalconConsoleDemo.csproj"
          $version = "${{ env.APP_VERSION }}"
          $content = Get-Content $csprojPath

          if ($content -notmatch "<Version>.*?</Version>") {
            # Insert <Version> tag inside the first PropertyGroup
            $content = $content -replace '(<PropertyGroup>)', "`$1`n    <Version>$version</Version>"
          } else {
            # Replace existing <Version> tag
            $content = $content -replace '(<Version>).*?(</Version>)', "`$1$version`$2"
          }

          $content | Set-Content $csprojPath
        shell: powershell


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build self-contained executable
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=false -p:Version=${{ env.APP_VERSION }} -o publish

      - name: Debug publish output
        run: dir publish
        shell: powershell

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/ZentrixLabs.FalconConsoleDemo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
